# Database Connection Properties
db.url=jdbc:mysql://localhost:3306/investment_portfolio
db.user=root
db.password=gaoussou147

# Connection Pool Settings
db.pool.initialSize=5
db.pool.maxActive=10
db.pool.maxIdle=5
db.pool.minIdle=2